# Generated by Django 4.1.1 on 2022-09-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=False, verbose_name='Номер заказа')),
                ('price_usd', models.IntegerField(default=False, verbose_name='Цена, $')),
                ('price_rub', models.IntegerField(default=False, verbose_name='Цена, руб')),
                ('delivery_time', models.CharField(max_length=100, verbose_name='Срок поставки')),
            ],
        ),
    ]
